// PLEASE DO NOT EDIT THIS FILE, 
// IF YOU WANT ADD ANY CODE CREATE NEW JS INTO client-custom 
import axios from 'axios';
window.axios = axios;

window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
import "./client-custom/assetsNode.js";
import "./client-custom/confirm.js";
import "./client-custom/customerActions.js";
import "./client-custom/login.js";
import "./client-custom/paymentReceiptUploader.js";
import "./client-custom/safeForm.js";
import "./client-custom/tabControll.js";
import "./client-custom/windowLoader.js";

// Client component scripts
import "./client/header.js";
import "./client/home.js";
import "./client/products.js";
import "./client/customer.js";
import "./client/gallery.js";
